config/routes.rb
Rails.application.routes.draw do
  root "books#top"
  get "home/about" => "books#about"
  devise_for :users, controllers: {
        sessions:      'users/sessions',
        registrations: 'users/registrations'
    }

  resources :books
  resources :users


    # see http://guides.rubyonrails.org/routing.html
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  attachment :profile_image
  has_many :books, dependent: :destroy
  validates :name, presence: true, length: { minimum:2 , maximum: 20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  
    before_action :configure_sign_up_params, only: [:create]
    before_action :configure_account_update_params, only: [:update]
 
    protected
    def configure_sign_up_params
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email])
    end
 
    def configure_account_update_params
        devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email])
    end

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]
 
    protected
    def configure_sign_in_params
        devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
    end



  # before_action :configure_sign_in_params, only: [:create]


  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    user = current_user
    @users = User.all
    @book = Book.new
  end
  def show
    @user = User.find(params[:id])
    @book = Book.new
  end
  def edit
    @user = User.find(params[:id])
    if  @user.id != current_user.id
        redirect_to user_path(current_user)
    end
  end
  def update
    @user = User.find(params[:id])
          if  @user.update(user_params)
              flash[:notice] = "updated USER successfully."
              redirect_to user_path(@user.id)
          else
              flash[:notice] = "USER error"
              render :edit
          end
  end
  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>users edit</h1>

<h2>User info</h2>
<%= form_for(@user) do |f| %>
    <div>
        <label>Name</label>
        <%= f.text_field :name, id:"inputEmail", placeholder:"名前"%>
    </div>
    <div>
        <label>Image</label>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
    </div>
    <div>
        <label>Introduction</label>
        <%= f.text_area :introduction, placeholder:"自己紹介 最大５０文字"%>
        <%= f.submit "Update User"%>
    </div>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">

        <div class='col-xs-3'>
          <h1>users index</h1>
          <h1>User info</h1>
                <%= attachment_image_tag current_user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpeg" ,size:'150x150'%>
            <table class="table">
                <tr>
                    <td><p>name</p></td>
                    <td><p><%= current_user.name%></p></td>
                </tr>
                <tr>
                    <td><p>introduction</p></td>
                    <td><p><%= current_user.introduction%></p></td>
                </tr>
            </table>

            <p><%= link_to "edit", edit_user_path(current_user) %></p><br>

            <h2>New book</h2>
            <%= form_for(@book) do |f| %>
              <% if @book.errors.any? %>
                <div id="error_explanation">
                  <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
                  <ul>
                  <% @book.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>
              <h5>Title</h5>
                <div class="form-group">
                    <%= f.text_field :title %>
                </div>
              <h5>Opinion</h5>
              <div class="from-group">
                <%= f.text_area :body %><br>
              </div>
                <%= f.submit 'Create Book' %>
            <% end %>
        </div>

        <div class='col-xs-9'>
          <h2>User</h2>
            <table class="table" border="1">
                <thead>
                   <tr>
                      <th>image</th>
                      <th>name</th>
                      <th></th>
                   </tr>
                </thead>
                <tbody>
                    <% @users.each do |user| %>
                      <tr>
                        <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: 'no_image.jpeg' , size:'50x50' %></td>
                        <td><%= user.name %></td>
                        <td><%= link_to 'Show', user_path(user) %></td>
                      </tr>
                    <% end %>
                </tbody>
            </table>
        </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
                <div class='col-xs-3'>
                <h1>User info</h1>
                        <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpeg" ,size:'150x150'%>
                    <table class="table">
                        <tr>
                            <td><p>name</p></td>
                            <td><p><%= @user.name%></p></td>
                        </tr>
                        <tr>
                            <td><p>introduction</p></td>
                            <td><p><%= @user.introduction%></p></td>
                        </tr>
                    </table>

                    <% if @user.id == current_user.id %>
                      <%= link_to 'edit', edit_user_path(@user.id) %>
                      <% end %>

                    <h2>New book</h2>
                    <%= form_for(@book) do |f| %>
                    <% if @book.errors.any? %>
                      <div id="error_explanation">
                        <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
                        <ul>
                        <% @book.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                        </ul>
                      </div>
                    <% end %>
                    
                    <h5>Title</h5>
                    <%= f.text_field :title %>

                    <h5>Opinion</h5>
                    <%= f.text_area :body %>

                    <%= f.submit 'Create Book' %>

                <% end %>
                </div>

                <div class='col-xs-9'>
                <h2>Books</h2>
                    <table class="table" border="1">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Title</th>
                                <th>Opinion</th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @user.books.each do |book| %>
                              <tr>
                                <td><%= link_to user_path(book.user.id) do %>
                                    <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: 'no_image.jpeg' , size:'50x50' %>
                                        <% end %>
                                    </td>
                                <td><%= link_to book.title,book_path(book) %></td>
                                <td><%= book.body %></td>
                              </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>

  </div>
</div>