config/routes.rb
Rails.application.routes.draw do
  root "books#top"
  get "home/about" => "books#about"
  devise_for :users, controllers: {
        sessions:      'users/sessions',
        registrations: 'users/registrations'
    }

  resources :books
  resources :users


    # see http://guides.rubyonrails.org/routing.html
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200 }

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!,except: [:about,:top]
  
  def index
        @book = Book.new
        @books = Book.all
        @user = @book.user
    end
    def create
        book = Book.new(book_params)
        book.user_id = current_user.id
                if  book.save
                    flash[:notice] = "successfully"
                    redirect_to book_path(book.id)
                else
                    flash.now[:alert] = 'error'
                    @books = Book.all
                    @book = book
                    render :index
                end
    end
    def destroy
        book = Book.find(params[:id])
        book.destroy
        redirect_to books_path
    end
    def show
        @book = Book.find(params[:id])
        @user = @book.user
        @newbook = Book.new
    end
    def update
        @book = Book.find(params[:id])
                @book.update(book_params)
             if @book.save
                flash[:notice] = "updated book successfully."
                redirect_to book_path(@book)
             else
                @user = current_user
                @books = Book.all
                flash[:notice]  = "error"
                render :edit
             end
    end
    def edit
        @book=Book.find(params[:id])
        if  @book.user_id == current_user.id
            render :edit
        else
            redirect_to books_path
        end
    end
    def top
    end
    def about
    end

    private
    def book_params
        params.require(:book).permit(:title,:body,:user_id)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/about.html.erb
h1>Welcome to</h1>
<h1 class="glyphicon glyphicon-book" aria-hidden="true">Bookers!!!</h1>

app/views/books/edit.html.erb
<h2>Editing Book</h2>
<%= form_for(@book) do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Opinion</h4>
    <%= f.text_area :body %><br>
    <%= f.submit "Update Book" %>
<% end %>

<%= link_to "Show",book_path %>
|
<%= link_to "Back",books_path %>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    
    <div class='col-xs-3'>
      <h1>books index</h1>
      <h1>User info</h1>
              <%= attachment_image_tag current_user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "profile-img", fallback: "no_image.jpeg" ,size:'150x150'%>
          <table class="table">
              <tr>
                  <td><p>name</p></td>
                  <td><p><%= current_user.name%></p></td>
              </tr>
              <tr>
                  <td><p>introduction</p></td>
                  <td><p><%= current_user.introduction%></p></td>
              </tr>
          </table>

          <p><%= link_to "edit", edit_user_path(current_user) %></p><br>

          <h2>New book</h2>
          <%= form_for(@book) do |f| %>
          <% if @book.errors.any? %>
            <div id="error_explanation">
              <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
              <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
       
          <h5>Title</h5>
          <%= f.text_field :title %>
       
          <h5>Opinion</h5>
          <%= f.text_area :body %>
       
          <%= f.submit 'Create Book' %>
      <% end %>
    </div>

    <div class='col-xs-9'>
      <h2>Books</h2>
      <table class="table table-striped" border="1">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book|%>
              <tr>
                <td><%= link_to user_path(book.user.id) do %>
                    <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg',fallback: "no_image.jpg" ,size:'50x50'%>
                    <% end %>
                </td>
                <td><%= link_to book.title,book_path(book) %></td>
                <td><%= book.body %></td>
              </tr>
            <%end%>
          </tbody>
        </table>
    </div>

  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">

        <div class='col-xs-3'>
            <h1>show book</h1>
                <h1>User info</h1>
                <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "profile-img", fallback: "no_image.jpeg" ,size:'150x150'%>
            <table class="table">
                <tr>
                    <td><p>name</p></td>
                    <td><p><%= @user.name%></p></td>
                </tr>
                <tr>
                    <td><p>introduction</p></td>
                    <td><p><%= @user.introduction%></p></td>
                </tr>
            </table>

            <% if @user.id == current_user.id %>
              <%= link_to '編集', edit_user_path(@user.id) %>
            <% end %>

            <h2>New book</h2>
            <%= form_for(@newbook) do |f| %>
            <% if @newbook.errors.any? %>
                <div id="error_explanation">
                  <h2><%= @newbook.errors.count %> errors prohibited this obj from being saved:</h2>
                  <ul>
                  <% @newbook.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
            <% end %>

            <h5>Title</h5>
            <%= f.text_field :title %>

            <h5>Opinion</h5>
            <%= f.text_area :body %>

            <%= f.submit 'Create Book' %>
            <% end %>
        </div>

        <div class='col-xs-9'>
          <h2>Book detail</h2>
          <table class='table table-hover'>
            <tbody>
                      <tr>
                        <td><%= link_to user_path(@book.user) do %>
                                <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: 'no_image.jpeg' , size:'50x50' %>
                                <%= @user.name %>
                            <% end %>
                        </td>
                        <td><%= link_to @book.title,book_path(@book) %></td>
                        <td><%= @book.body %></td>
                        <% if user_signed_in? && @book.user_id == current_user.id %>
                        <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-primary" %></td>
                        <td><%= link_to 'Destroy', book_path(@book), method: :delete, "data-confirm" => "Are you sure?", class: "btn btn-danger" %></td>
                      </tr>
                        <% end %>
            </tbody>
          </table>
        </div>

  </div>
</div>

app/views/books/top.html.erb
<main>
	<div class="title">welcome to<br>
		<span class="glyphicon glyphicon-book" aria-hidden="true"></span>
	Bookers  !! </div>
</main>
<div class="main_text">
In <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
Bookers,<br><br>
you can share and exchange your opinions , inpressions , and<br>emotions<br><br>
about various books!<br><br>

<div class="row">
  <p><a class="btn btn-info col-xs-3 col-xs-offset-4 sign_in" href="/users/sign_in">Log in</a></p>
</div>
<div class="row">
  <p><a class="btn btn-warning col-xs-3 col-xs-offset-4 sign_up" href="/users/sign_up">Sign Up</a></p>
</div>


<footer>CopyRight Infratop.inc</footer>