config/routes.rb
Rails.application.routes.draw do
  root "books#top"
  get "home/about" => "books#about"
  devise_for :users, controllers: {
        sessions:      'users/sessions',
        registrations: 'users/registrations'
    }

  resources :books
  resources :users


    # see http://guides.rubyonrails.org/routing.html
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_massages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_massages.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>">
      <%= message %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header class="navbar navbar-inverse">
    <div class="container-fluid">
      <nav class="nav navbar-nav navbar-left">
        <h2>Bookers</h2>
      </nav>
      <nav class="nav navbar-nav  navbar-right">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>


      <div class="collapse navbar-collapse" id="navbarEexample7">
              <ul class="nav navbar-nav">
              <% if user_signed_in? %>
                <li class="">
                  <%= link_to " Home", user_path(current_user.id), class: "glyphicon glyphicon-home home"%>
                </li>
                <li class="">
                  <%= link_to " Users", users_path, class: "glyphicon glyphicon-user users" %>
                </li>
                <li class="">
                  <%= link_to " Books", books_path, class: "glyphicon glyphicon-book books" %>
                </li>
                <li class="">
                  <%= link_to " logout", destroy_user_session_path,method: :delete, class: "glyphicon glyphicon-log-out logout" %>
                  </li>
              <% else %>
                <li class="">
                  <%= link_to " Home", root_path, class: "glyphicon glyphicon-home home" %>
                  </li>
                <li class="">
                  <%= link_to " About", home_about_path, class: "glyphicon glyphicon-link about" %>
                  </li>
                <li class="">
                  <%= link_to " Sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %>
                  </li>
                <li class="">
                  <%= link_to " login", new_user_session_path, class: "glyphicon glyphicon-log-in sign_in" %>
                  </li>
              <%end%>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </div>
  </header>
 <div class="container">
  <p id="notice">
    <%= notice %>
  </p>

    <%= yield %>
 </div>
  </body>
</html>